# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8d8b3e0024025dc365fdfe148a7f5f6b132b04efe5e23a86fc809d493ca2547011e9168efe17f9a2741f93ce0b7e2a4a27d351b364a1d02c1b91d0b60998fdec

test:
  secret_key_base: bba4dbd1221a061efc7700e886bda717a9a2d65b353b8a8d437560f53a0748bca6a88ecc98d77c0e50714ef6441da02ce3e7e481084f07f3495ab85e1fc9e532

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
